### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by IFlexMyBallz** [afkarxyz/misc-scripts#1]
I added the script to Thampermonkey from "GreasyFork" and i tried it out and nothing happened, so i pasted it into the browser console and the button did appear but It did not download anything
for instance i am on the Raspberry Pi running this on Chromium (Rpi os 64-Bit)

**Comment by afkarxyz** [comment]
Can you elaborate? Which script and what kind of error? Because I installed all these scripts and there was no problem.
